# Generated by Django 5.1.1 on 2024-10-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='nama',
            new_name='name',
        ),
    ]
