# Generated by Django 5.1.1 on 2024-10-07 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_nama_location_name'),
        ('restaurant', '0005_remove_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
