# Generated by Django 5.1.1 on 2024-10-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='restaurant',
        ),
    ]
