# Generated by Django 5.1.1 on 2024-10-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_restaurant'),
        ('restaurant', '0007_remove_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
