# Generated by Django 5.1.2 on 2024-10-24 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_location_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='trivia',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
