# Generated by Django 5.1.2 on 2024-10-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_location_trivia_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='trivia',
            field=models.TextField(default=None),
        ),
    ]
