# Generated by Django 5.1.1 on 2024-10-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_location_trivia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='trivia',
            field=models.TextField(),
        ),
    ]
