# Generated by Django 5.1.1 on 2024-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_fnb_forum_user_forumkhusus'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
