# Generated by Django 5.1.1 on 2024-10-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
    ]
