# Generated by Django 5.1.2 on 2024-10-24 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forum_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.AddField(
            model_name='forum',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='forumkhusus',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
