# Generated by Django 5.1.1 on 2024-10-26 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_forumkhusus_forum_forum_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_khusus', to='forum.forumkhusus'),
            preserve_default=False,
        ),
    ]
