# Generated by Django 5.1.1 on 2024-10-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_forum_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='comment',
        ),
        migrations.AddField(
            model_name='forumkhusus',
            name='forum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='forum_khusus', to='forum.forum'),
            preserve_default=False,
        ),
    ]
