# Generated by Django 5.1.2 on 2024-10-23 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='fnb',
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default=0),
        ),
    ]
