# Generated by Django 5.1.2 on 2024-10-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0002_fnb_user'),
        ('review', '0002_remove_review_fnb_review_like_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='makanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fnb.fnb'),
            preserve_default=False,
        ),
    ]
