# Generated by Django 5.1.1 on 2024-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0002_fnb_user'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='fnb',
            field=models.ManyToManyField(related_name='fnb', to='fnb.fnb'),
        ),
    ]
