# Generated by Django 5.1.1 on 2024-12-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0002_fnb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnb',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
