# Generated by Django 5.1.1 on 2024-10-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_nama_location_name'),
        ('restaurant', '0002_restaurant_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='nama',
            new_name='name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
            preserve_default=False,
        ),
    ]
