# Generated by Django 5.1.1 on 2024-10-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnb', '0002_fnb_user'),
        ('restaurant', '0003_rename_nama_restaurant_name_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='fnb',
            field=models.ManyToManyField(related_name='restaurant_fnb', to='fnb.fnb'),
        ),
    ]
