# Generated by Django 5.1.1 on 2024-10-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
    ]
