# Generated by Django 5.1.1 on 2024-10-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_location_restaurant'),
        ('restaurant', '0007_remove_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
            preserve_default=False,
        ),
    ]
